### ISSUE TITLE
Cordova 2.8.0 raising no method 'overrideBackbutton'

### ISSUE THREAD

**Issue by marcoslin** [ajoslin/angular-mobile-nav#59]
Hi,

I am having an issue with angular-mobile-nav on the very initial page load of Cordova 2.8 Android project using Ripple Emulator.  The error I am getting is:

```
TypeError: Object #<Object> has no method 'overrideBackbutton'
    at module.exports.exec (chrome-extension://geelfhphabnejjhdalkjhgipohgpdnoc/ripple.js:40:22917)
    at backButtonChannel.onHasSubscribersChange (http://localhost:8076/cordova.js:1145:13)
    at Channel.subscribe (http://localhost:8076/cordova.js:667:49)
    at HTMLDocument.document.addEventListener (http://localhost:8076/cordova.js:132:34)
    at null.<anonymous> (http://localhost:8076/components/mobile-nav/mobile-nav.js:11:14)
    at Channel.fire (http://localhost:8076/cordova.js:709:23)
    at http://localhost:8076/cordova.js:232:47
```

Basically, it is cause by mobile-nav.js line 11:
`document.addEventListener("backbutton", function() {`

And error raised by cordova.js' call originating from line 1145:
`exec(null, null, "App", "overrideBackbutton", [this.numHandlers == 1]);`

Is this a problem that you can replicate?  Any help would be greatly appreciated.

Mean while, investigation continues on my part...

**Comment by marcoslin** [comment]
This turn out to be a Ripple specific problem. The answer on my [stackoverflow](http://stackoverflow.com/questions/17250796/phonegap-2-8-0-raising-no-method-overridebackbutton-with-angular-mobile-nav) question solved the problem for me.
